# Generated by Django 2.1 on 2019-04-27 22:03

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190427_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=project.models.get_image_filename, verbose_name='Image'),
        ),
    ]
