# Generated by Django 2.0.13 on 2019-04-29 11:34

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190429_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=project.models.get_image_filename, verbose_name='Image'),
        ),
    ]
