# Generated by Django 2.2 on 2019-04-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProf',
        ),
    ]
