# Generated by Django 2.2 on 2019-04-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190427_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProf',
        ),
    ]
