# Generated by Django 2.2 on 2019-04-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProf',
        ),
    ]
