# Generated by Django 2.2 on 2019-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_delete_userprof'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('facebook_profile', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='user/images/%Y/%m/%d/')),
            ],
        ),
    ]
