# Generated by Django 2.2 on 2019-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.FileField(blank=True, upload_to='profile_image'),
        ),
    ]
